spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/provaApollus
    username: provaApollus
    password: provaApollus
  jpa:
    hibernate:
      ddl-auto: validate
server:
  error:
    include-message: always
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
token:
  secret: ${JWT_SECRET:my-secret-key}


